version: 1.2
workflows:
  # --------------------
  # Annotation Workflows
  # --------------------
  - subclass: WDL
    name: AnnotateAgeMetrics
    primaryDescriptorPath: /wdl/annotation/AnnotateAgeMetrics.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateCallsetOverlap
    primaryDescriptorPath: /wdl/annotation/AnnotateCallsetOverlap.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateDbSNP
    primaryDescriptorPath: /wdl/annotation/AnnotateDbSNP.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateDbVaR
    primaryDescriptorPath: /wdl/annotation/AnnotateDbVaR.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateIndelTRs
    primaryDescriptorPath: /wdl/annotation/AnnotateIndelTRs.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateInSilicoPredictors
    primaryDescriptorPath: /wdl/annotation/AnnotateInSilicoPredictors.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateGnomADSTR
    primaryDescriptorPath: /wdl/annotation/AnnotateGnomADSTR.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateGQMetrics
    primaryDescriptorPath: /wdl/annotation/AnnotateGQMetrics.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateL1MEAID
    primaryDescriptorPath: /wdl/annotation/AnnotateL1MEAID.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateMEDs
    primaryDescriptorPath: /wdl/annotation/AnnotateMEDs.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateMEIs
    primaryDescriptorPath: /wdl/annotation/AnnotateMEIs.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotatePALMER
    primaryDescriptorPath: /wdl/annotation/AnnotatePALMER.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateRegion
    primaryDescriptorPath: /wdl/annotation/AnnotateRegion.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateSQMetrics
    primaryDescriptorPath: /wdl/annotation/AnnotateSQMetrics.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateSVAN
    primaryDescriptorPath: /wdl/annotation/AnnotateSVAN.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateSVAnnotate
    primaryDescriptorPath: /wdl/annotation/AnnotateSVAnnotate.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateTruvariRemap
    primaryDescriptorPath: /wdl/annotation/AnnotateTruvariRemap.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateVEPHail
    primaryDescriptorPath: /wdl/annotation/AnnotateVEPHail.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateVRS
    primaryDescriptorPath: /wdl/annotation/AnnotateVRS.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  # --------------------
  # Annotation Utilities
  # --------------------
  - subclass: WDL
    name: AddEndTRs
    primaryDescriptorPath: /wdl/annotation_utils/AddEndTRs.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateAlleleType
    primaryDescriptorPath: /wdl/annotation_utils/AnnotateAlleleType.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateVcf
    primaryDescriptorPath: /wdl/annotation_utils/AnnotateVcf.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateVcfCleared
    primaryDescriptorPath: /wdl/annotation_utils/AnnotateVcfCleared.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: CombineTRs
    primaryDescriptorPath: /wdl/annotation_utils/CombineTRs.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: ConcatenateMosDepth
    primaryDescriptorPath: /wdl/annotation_utils/ConcatenateMosDepth.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: CountAnnotations
    primaryDescriptorPath: /wdl/annotation_utils/CountAnnotations.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: CreateCohortMethylationFile
    primaryDescriptorPath: /wdl/annotation_utils/CreateCohortMethylationFile.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: CreateCoverageFile
    primaryDescriptorPath: /wdl/annotation_utils/CreateCoverageFile.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: CreateDepthFiles
    primaryDescriptorPath: /wdl/annotation_utils/CreateDepthFiles.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: CreateMetadataFile
    primaryDescriptorPath: /wdl/annotation_utils/CreateMetadataFile.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: CreateReadCountsFile
    primaryDescriptorPath: /wdl/annotation_utils/CreateReadCountsFile.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: DropGenotypes
    primaryDescriptorPath: /wdl/annotation_utils/DropGenotypes.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: ExtractSampleVcfs
    primaryDescriptorPath: /wdl/annotation_utils/ExtractSampleVcfs.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: FillPhasedGenotypes
    primaryDescriptorPath: /wdl/annotation_utils/FillPhasedGenotypes.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: GenerateTRGTJson
    primaryDescriptorPath: /wdl/annotation_utils/GenerateTRGTJson.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: IntegrateTRs
    primaryDescriptorPath: /wdl/annotation_utils/IntegrateTRs.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: IntegrateVcfs
    primaryDescriptorPath: /wdl/annotation_utils/IntegrateVcfs.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: MergeBackbonePhased
    primaryDescriptorPath: /wdl/annotation_utils/MergeBackbonePhased.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: PlotPhasingResults
    primaryDescriptorPath: /wdl/annotation_utils/PlotPhasingResults.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: PostProcess
    primaryDescriptorPath: /wdl/annotation_utils/PostProcess.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: ResolveHaplotypeOverlaps
    primaryDescriptorPath: /wdl/annotation_utils/ResolveHaplotypeOverlaps.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: SubsetTsvToColumns
    primaryDescriptorPath: /wdl/annotation_utils/SubsetTsvToColumns.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: TransformAlleleType
    primaryDescriptorPath: /wdl/annotation_utils/TransformAlleleType.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: VcfToBed
    primaryDescriptorPath: /wdl/annotation_utils/VcfToBed.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: MakeDepthMetrics
    primaryDescriptorPath: /wdl/annotation_utils/MakeDepthMetrics.wdl
    filters:
      branches:
        - main
        - gcnv
      tags:
        - /.*/

  # -----
  # Tools
  # -----
  - subclass: WDL
    name: Automop
    primaryDescriptorPath: /wdl/tools/Automop.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: BackbonePhase
    primaryDescriptorPath: /wdl/tools/BackbonePhase.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: HiFiCNV
    primaryDescriptorPath: /wdl/tools/HiFiCNV.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: HiPhase
    primaryDescriptorPath: /wdl/tools/HiPhase.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: HiPhaseMerge
    primaryDescriptorPath: /wdl/tools/HiPhaseMerge.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: Kanpig
    primaryDescriptorPath: /wdl/tools/Kanpig.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: LRCNVs
    primaryDescriptorPath: /wdl/tools/LRCNVs.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: MethylationProfiling
    primaryDescriptorPath: /wdl/tools/MethylationProfiling.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/
  
  - subclass: WDL
    name: MinimapAlignment
    primaryDescriptorPath: /wdl/tools/MinimapAlignment.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: MosDepth
    primaryDescriptorPath: /wdl/tools/MosDepth.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: PALMER
    primaryDescriptorPath: /wdl/tools/PALMER.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: PALMERDiploid
    primaryDescriptorPath: /wdl/tools/PALMERDiploid.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: PALMERMerge
    primaryDescriptorPath: /wdl/tools/PALMERMerge.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: PAV
    primaryDescriptorPath: /wdl/tools/PAV.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: RepeatMasker
    primaryDescriptorPath: /wdl/tools/RepeatMasker.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: Sawfish
    primaryDescriptorPath: /wdl/tools/Sawfish.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: TRGT
    primaryDescriptorPath: /wdl/tools/TRGT.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: TRGTLPS
    primaryDescriptorPath: /wdl/tools/TRGTLPS.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: Vamos
    primaryDescriptorPath: /wdl/tools/Vamos.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: VcfDist
    primaryDescriptorPath: /wdl/tools/VcfDist.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: VcfDistCohort
    primaryDescriptorPath: /wdl/tools/VcfDistCohort.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: Whatshap
    primaryDescriptorPath: /wdl/tools/Whatshap.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: DepthPreprocessing
    primaryDescriptorPath: /wdl/tools/DepthPreprocessing.wdl
    filters:
      branches:
        - main
        - gcnv
      tags:
        - /.*/

  - subclass: WDL
    name: DepthClustering
    primaryDescriptorPath: /wdl/tools/DepthClustering.wdl
    filters:
      branches:
        - main
        - gcnv
      tags:
        - /.*/

  - subclass: WDL
    name: GenotypeDepth
    primaryDescriptorPath: /wdl/tools/GenotypeDepth.wdl
    filters:
      branches:
        - main
        - gcnv
      tags:
        - /.*/
  - subclass: WDL
    name: LongReadCNVs
    primaryDescriptorPath: /wdl/tools/LongReadCNVs.wdl
    filters:
      branches:
        - main
        - gcnv
