FROM us-central1-docker.pkg.dev/talkowski-sv-gnomad/kj-dockers/utils:latest

MAINTAINER Karan Jaisingh

ENV DEBIAN_FRONTEND=noninteractive

# Install sawfish
ARG SAWFISH_VERSION
RUN wget -q https://github.com/PacificBiosciences/sawfish/releases/download/${SAWFISH_VERSION}/sawfish-${SAWFISH_VERSION}-x86_64-unknown-linux-gnu.tar.gz \
    && tar xzf sawfish-${SAWFISH_VERSION}-x86_64-unknown-linux-gnu.tar.gz \
    && mv sawfish-${SAWFISH_VERSION}-x86_64-unknown-linux-gnu/bin/sawfish /usr/local/bin/ \
    && rm -rf sawfish-${SAWFISH_VERSION}-x86_64-unknown-linux-gnu* \
    && sawfish --version
