FROM us-central1-docker.pkg.dev/talkowski-sv-gnomad/kj-dockers/utils:latest

MAINTAINER Karan Jaisingh

RUN apt-get update && apt-get install --no-install-recommends --yes \
    procps \
    unzip \
    dpkg-dev \
    libgdbm-dev \
    libc6-dev \
    libsqlite3-dev \
    libffi-dev \
    libncurses5-dev \
    time \
    grabix \
    && rm -rf /var/lib/apt/lists/*

# Install htslib
ARG HTSLIB_VERSION
RUN wget -q https://github.com/samtools/htslib/releases/download/${HTSLIB_VERSION}/htslib-${HTSLIB_VERSION}.tar.bz2 \
	&& tar xjf htslib-${HTSLIB_VERSION}.tar.bz2 \
	&& rm htslib-${HTSLIB_VERSION}.tar.bz2 \
	&& cd htslib-${HTSLIB_VERSION} \
	&& ./configure --enable-libcurl --enable-gcs --enable-s3 \
	&& make \
    && make install \
    && cd / \
    && rm -rf htslib-${HTSLIB_VERSION}

# Install samtools
ARG SAMTOOLS_VERSION
RUN wget -q https://github.com/samtools/samtools/releases/download/${SAMTOOLS_VERSION}/samtools-${SAMTOOLS_VERSION}.tar.bz2 \
	&& tar xjf samtools-${SAMTOOLS_VERSION}.tar.bz2 \
	&& rm samtools-${SAMTOOLS_VERSION}.tar.bz2 \
	&& cd samtools-${SAMTOOLS_VERSION} \
	&& ./configure --enable-libcurl --enable-gcs --enable-s3 \
	&& make \
    && make install \
    && cd / \
    && rm -rf samtools-${SAMTOOLS_VERSION}

# Install bcftools
ARG BCFTOOLS_VERSION
RUN wget -q https://github.com/samtools/bcftools/releases/download/${BCFTOOLS_VERSION}/bcftools-${BCFTOOLS_VERSION}.tar.bz2 \
	&& tar xjf bcftools-${BCFTOOLS_VERSION}.tar.bz2 \
	&& rm bcftools-${BCFTOOLS_VERSION}.tar.bz2 \
	&& cd bcftools-${BCFTOOLS_VERSION} \
	&& ./configure \
	&& make \
    && make install \
    && cd / \
    && rm -rf bcftools-${BCFTOOLS_VERSION}

# Install bedtools
ARG BED_TOOLS_VERSION
RUN wget https://github.com/arq5x/bedtools2/releases/download/v${BED_TOOLS_VERSION}/bedtools.static \
    && chmod 755 bedtools.static \
	&& mv bedtools.static /usr/bin/bedtools

# Install TRF
RUN wget -q https://github.com/Benson-Genomics-Lab/TRF/releases/download/v4.09.1/trf409.linux64 \
    && chmod 755 trf409.linux64 \
    && mv trf409.linux64 /usr/bin/trf

RUN python3 -m pip install --no-cache-dir git+https://github.com/bw2/trviz@9068d9abc50ec9b8ba478505d3d19496e1f431b9 pyarrow



ENV HTSLIB_CONFIGURE_OPTIONS="--enable-s3 --enable-gcs --enable-libcurl --with-libdeflate"
ADD https://api.github.com/repos/broadinstitute/str-analysis/commits/main /opt/str-analysis-main.json
RUN str_analysis_commit="$(python3 -c 'import json; print(json.load(open("/opt/str-analysis-main.json"))["sha"])')" \
    && test -n "${str_analysis_commit}" \
    && python3 -m pip install --upgrade --no-cache-dir \
        configargparse \
        git+https://github.com/broadinstitute/str-analysis@${str_analysis_commit} \
    && printf '%s\n' "${str_analysis_commit}" > /opt/str-analysis-commit

ENV PYTHONPATH=/:.:$PYTHONPATH
