FROM us-central1-docker.pkg.dev/talkowski-sv-gnomad/kj-dockers/utils:latest

MAINTAINER Karan Jaisingh

ENV DEBIAN_FRONTEND=noninteractive

# Install whatshap
ARG WHATSHAP_VERSION
RUN pip3 install whatshap==${WHATSHAP_VERSION}
